plugins:
  - babel
  - jest
  - react

extends:
  - airbnb-base
  - "plugin:jest/recommended"
  - "plugin:react/recommended"

rules:
  "react/jsx-curly-spacing": ["error", "always"]

parser: babel-eslint

env:
  browser: true
  node: true
  jest: true
  es6: true

settings:
  react:
    version: "16.6"
  import/resolver:
    webpack:
      config: 'webpack.config.dev.babel.js'
